[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../.."

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[project]
name = "agentiq"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit"
]
readme = "pypi.md"
description = "Transitional package for aiqtoolkit, this package is deprecated and will be removed in the future."
classifiers = ["Programming Language :: Python"]
